name: Reusable Workflow
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: 'Name of the artifact to download'
        required: true
        default: 'dist'
        type: string
    outputs:
      result:
        description: 'Result of the deployment'
        value: ${{ steps.deploy.outputs.outcome }}
    #secrets:
      #some-secrets:
        #required: false

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: List contents
        run: ls 

      - name: Output information
        run: echo "Deploying & uploading..."

      - name: Set result output
        id: set-result
        run: echo "::set-output name=step-result::success"
      